version: "3.9"

services:
  backend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    image: topcenter-erpnext-dev:latest
    restart: unless-stopped
    environment:
      FRAPPE_SITE_NAME: erp.topcenter.local
      DB_HOST: db
      REDIS_QUEUE: redis-queue:6379
      REDIS_CACHE: redis-cache:6379
    volumes:
      - ../../apps:/home/frappe/frappe-bench/apps
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8000:8000"

volumes:
  sites:
  logs:

